version: '3'

services:
  zinza-training:
    build:
      context: ./
      dockerfile: docker/${APP_ENV}/Dockerfile
    image: zinza-training
    ports:
      - '3000:3000'
    volumes:
      - .:/app
